version : "3.7"
services:
  
  sql-server-db:
      container_name : sql-server-db
      image: mcr.microsoft.com/mssql/server:2022-latest
      environment:
        SA_PASSWORD: "super_duper_1234"
        ACCEPT_EULA: "Y"
      ports:
      - 4444:1433
  
  meetup_api:
    image: dotnet
    build:
      context: dotnet
      dockerfile: /MeetUp.Api/Dockerfile
    ports:
      - 7197:80
  
  node:
    build:
      context: nodeJs
      dockerfile: /Dockerfile
    ports:
      - 8000:8000
  
  react:
    build:
      context: react
      dockerfile: /Dockerfile
    ports:
      - 3000:3000